# Generated by Django 4.1.5 on 2023-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEMPapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSMSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HUMIDITY', models.FloatField(default=0)),
                ('DATE', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='DHT11Model',
        ),
    ]
