# Generated by Django 4.2 on 2023-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TEMPapp", "0002_csmsmodel_delete_dht11model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PumpingValueModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
